/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ContentSearchResult {
  author: string
  novelId: number
  novelTitle: string
  chapterId: string
  chapterTitle: string
  chapterIndex: number
}

export declare function searchContent(keyword: string, page: number): Array<ContentSearchResult>
