/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AuthorSearchResult {
  author: string
  novelId: number
  novelTitle: string
  chapterCount: number
  wordCount: number
}

export interface ChapterInfo {
  id: string
  chapterIndex: number
  title: string
  wordCount: number
}

export interface ChapterResult {
  title: string
  content: string
}

export interface ContentSearchResult {
  author: string
  novelId: number
  novelTitle: string
  chapterId: string
  chapterTitle: string
  chapterIndex: number
}

export declare function getChapter(id: string, novelId: number): ChapterResult | null

export declare function getNovel(id: number): NovelResult | null

export interface NovelResult {
  author: string
  novelId: number
  novelTitle: string
  chapterCount: number
  wordCount: number
  chapterInfo: Array<ChapterInfo>
}

export interface NovelSearchResult {
  author: string
  novelId: number
  novelTitle: string
  chapterCount: number
  wordCount: number
}

export declare function searchAuthor(keyword: string, page: number): Array<AuthorSearchResult>

export declare function searchContent(keyword: string, page: number): Array<ContentSearchResult>

export declare function searchNovel(keyword: string, page: number): Array<NovelSearchResult>
