/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ContentSearchResponse {
	results: Array<ContentSearchResult>;
	total: number;
}

export interface ContentSearchResult {
	author: string;
	novelId: number;
	novelTitle: string;
	chapterId: string;
	chapterTitle: string;
	chapterIndex: number;
}

export interface DownloadChapter {
	title: string;
	data: string;
}

export interface DownloadChapter {
	title: string;
	data: string;
}

export interface DownloadNovel {
	title: string;
	author: string;
}

export interface DownloadNovel {
	title: string;
	author: string;
}

export interface DownloadResult {
	title: string;
	author: string;
	chapters: Array<DownloadChapter>;
}

export interface DownloadResult {
	title: string;
	author: string;
	chapters: Array<DownloadChapter>;
}

export declare function generateEpub(downloadResult: DownloadResult): Buffer;

export declare function generateSvevnz(downloadResult: DownloadResult): Buffer;

export interface NovelSearchResponse {
	results: Array<NovelSearchResult>;
	total: number;
}

export interface NovelSearchResult {
	author: string;
	novelId: number;
	novelTitle: string;
}

export declare function searchAuthor(
	keyword: string,
	page: number,
): Promise<NovelSearchResponse>;

export declare function searchContent(
	keyword: string,
	page: number,
): Promise<ContentSearchResponse>;

export declare function searchTitle(
	keyword: string,
	page: number,
): Promise<NovelSearchResponse>;
